FROM oraclelinux:8.3

RUN set -ex && \
    groupadd www && \
    useradd -m -g www wwwrun && \
    dnf module install php:7.4 -y && \
    dnf install -y \
        php \
        php-embedded \
        unzip \
        which \
        urw-base35-nimbus-sans-fonts && \
    dnf install -y https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox-0.12.6-1.centos8.x86_64.rpm && \
    dnf clean all &&\
  	rm -rf /var/cache/yum

WORKDIR /app
